### ISSUE TITLE
Unhandled Error when trying to upload an article that is too big

### ISSUE THREAD

**Issue by gbrivady** [iScsc/iscsc.fr#14]
Trying to upload an article that is too big causes an error in the backend; I produced this error by trying to upload a 64ko file as a markdown article.

The preview worked fine, but pressing the "Add article" button creates the following error (see end of message) in the **backend**. 
From the user's perspective, nothing happened as no new article is created, and no error is reported.

**Details:**
- OS: Windows 10
- npm version: 8.19.1
- node version: 18.9.1

Error message:
```
PayloadTooLargeError: request entity too large
    at readStream (C:\Users\*****\Documents\repo\site\backend\node_modules\raw-body\index.js:156:17)
    at getRawBody (C:\Users\*****\Documents\repo\site\backend\node_modules\raw-body\index.js:109:12)
    at read (C:\Users\*****\Documents\repo\site\backend\node_modules\body-parser\lib\read.js:79:3)
    at jsonParser (C:\Users\*****\Documents\repo\site\backend\node_modules\body-parser\lib\types\json.js:135:5)
    at Layer.handle [as handle_request] (C:\Users\*****\Documents\repo\site\backend\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\*****\Documents\repo\site\backend\node_modules\express\lib\router\index.js:328:13)
    at C:\Users\*****\Documents\repo\site\backend\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\Users\*****\Documents\repo\site\backend\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Users\*****\Documents\repo\site\backend\node_modules\express\lib\router\index.js:280:10)
    at expressInit (C:\Users\*****\Documents\repo\site\backend\node_modules\express\lib\middleware\init.js:40:5)
```

**Comment by atxr** [comment]
Thanks for reporting this issue.
I think I will add a size limit but I don't know how much. Any suggestion?

**Comment by gbrivady** [comment]
I think adding a size limit to uploaded files should be enough, but we should also display an error message to the user, so they knows why nothing is happening. 

Maybe also throw a character limit to all the text fields of article creation, to prevent copy/pasting long texts?

**Comment by atxr** [comment]
> Maybe also add a character limit to all the text fields of article creation, to prevent copy/pasting long texts?

Yes indeed let's do this also

**Comment by atxr** [comment]
How big should be the size limit for the files?
